import FullSidebarAccordion from "./components/SidebarAccordian";
import GlobalDiceRoller from "./components/GlobalDiceRoller";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <FullSidebarAccordion />
          <GlobalDiceRoller />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
