import FullSidebarAccordion from './components/SidebarAccordian';
import GlobalDiceRoller from './components/GlobalDiceRoller';
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <FullSidebarAccordion />
        <GlobalDiceRoller />
        {children}
      </body>
    </html>
  )
}